name: TGraphDB (http-server) Docker Image v4.4

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout default branch
      uses: actions/checkout@v4
    
    - name: Set env variable
      run: |
        echo "BUILD_TIME=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "COMMIT_SHA_SHORT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
        echo ${{env.BUILD_TIME}}
        echo ${{env.COMMIT_SHA_SHORT}}
    
    - name: Login to hub.docker.com
      uses: docker/login-action@v3
      with:
        username: songjinghe
        password: ${{ secrets.dockerhub }}
    
    - name: Build and Push Docker Image (tgraph4.4-http-server)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          songjinghe/tgraphdb:http-4.4-${{env.COMMIT_SHA_SHORT}}
          songjinghe/tgraphdb:http-4.4-latest
